module.exports = {
	aliases: [/en([-_](au|bz|ca|cb|gb|in|ie|jm|nz|ph|za|tt|us))?/, "english"],
	no_translation: 'UNTRANSLATED STRING',
	select_mode_arrows: 'Select Mode to use with the arrow keys, then press enter to confirm.',
	change_options: 'To change any options (all of which are optional), press the corresponding button. When you are done, press enter.',
	change_options_k: 'To change any options (all of which except the keyframe file are optional), press the corresponding button. When you are done, press enter.',
	current_arg_values: 'currently set argument values:',
	enter_arg_value: 'Please enter your desired value for the argument "{arg}", then press enter to confirm. Escape to Cancel.',
	enter_file_path: 'Please enter the path to the file you wish to convert (including file name and, if applicable, extension)',
	review_settings: 'These are the settings you selected. If you want to proceed, press Enter. If not, exit the program (Q or Ctrl+C)',
	r_s_mode: 'Mode:',
	r_s_args: 'Modified Arguments:',
	r_s_file: 'Selected File:',
	tui_done: 'Done! Press any key to close this interface.',
	file_not_found: 'File does not exist!',
	keyframes_file_needed: 'You need to set the keyframes argument.',
	// leave "%s" in these; it gets replaced by the relevant warning/error at runtime
	warning_template: "[WARNING] %s",
	error_template: "[ERROR] %s",
	parsing_keyframes: 'Parsing Keyframe File {file}...',
	load_mode_failed: 'mode: {mode} load failed',
	flag_locale_desc: 'Sets the used language',
	illegal_argument: 'Illegal argument: {arg}',
	arg_cannot_be_set: 'Argument {arg} cannot be set.',
	no_mode_selected: 'No mode selected, using default "{default}"',
	kf_file_not_found: 'KeyFrame file {file} was not found.',
	kf_file_required: 'KeyFrame file is required, but none was given.',
	no_video_file: 'No input video file was given.',
	video_file_not_found: 'Video file not found: "{file}"',
	info1: 'Input file: {video}.\nUsing minimum w/h {delta}px.\nExtracting necessary input file info...',
	info2: 'Resolution is {w}x{h}.\nFramerate is {framerate} ({decframerate}).\nInput Bitrate is {bitrate}.',
	config_header: '============Config============',
	config_footer: '==============================',
	config_mode_list: 'Modes: {modes}',
	bounce_speed: 'Bounce Speed: {tempo} times per second',
	rotate_speed: 'Rotation Speed: {angle}° per second',
	keyframe_file: 'Keyframe file: {file}',
	output_bitrate: 'Output Bitrate: {bitrate}',
  creating_temp_dirs: 'Creating temporary directories...',
	splitting_audio: 'Splitting audio into a temporary file...',
	no_audio: 'No audio detected.',
	splitting_frames: 'Splitting file into frames...',
	starting_conversion: 'Converting frames to webm...',
	convert_progress: 'Converting {framecount} frames to webm (frames {startframe}-{endframe} / {batch_size}) - {percent}%',
	done_conversion: 'Successfully converted all {framecount} frames in {time}ms',
	writing_concat_file: 'Writing concat file...',
	concatenating: 'Concatenating segments into final webm file',
	concatenating_audio: 'Concatenating segments and applying audio to final webm file',
	done_removing_temp: 'Done!\nRemoving temporary files...'
}