on:
  push:
    branches:
      - 'main'
      - 'shadow**'

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run script"
        run: node .github/format.js
      - name: "Commit changes"
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_message: "Update scripts with the modes from the /modes directory"
          force: false
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Replaced foo/bar"
          title: ${{ github.event.commits[0].message }}
          label: automation
          reviewer: thewilloftheshadow
          
