on:
  push:
    branches:
      - 'main'
      - 'shadow**'

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Run script"
        run: node .github/format.js
